/*
 * formfillm — shared type definitions
 *
 * These types are the contract between the content script, the background
 * service worker, and the side panel. Keeping them in one dependency-free
 * module means the privacy-critical logic (sensitivity, redaction, policy)
 * can be unit-tested without any Chrome APIs.
 */

// ---------------------------------------------------------------------------
// Field categories — what a form field is asking for.
// ---------------------------------------------------------------------------

export const FIELD_CATEGORIES = [
  "identity.full_name",
  "identity.first_name",
  "identity.last_name",
  "identity.username",
  "contact.email",
  "contact.phone",
  "address.street",
  "address.unit",
  "address.city",
  "address.region",
  "address.postal_code",
  "address.country",
  "locale.language",
  "locale.region",
  "preference.communication",
  "preference.generic",
  "employment.job_title",
  "employment.company",
  "demographic.birthdate",
  "demographic.gender",
  "government_id",
  "health",
  "financial",
  "password",
  "secret",
  "unknown",
] as const;

export type FieldCategory = (typeof FIELD_CATEGORIES)[number];

// ---------------------------------------------------------------------------
// Sensitivity — how careful we must be with a disclosure.
// ---------------------------------------------------------------------------

export const SENSITIVITIES = ["low", "medium", "high", "secret", "unknown"] as const;
export type Sensitivity = (typeof SENSITIVITIES)[number];

// ---------------------------------------------------------------------------
// Recommended action — what the assistant proposes for a field.
// ---------------------------------------------------------------------------

export const RECOMMENDED_ACTIONS = [
  "approve_candidate", // low sensitivity, safe to batch-approve after display
  "ask", // medium sensitivity, ask per field
  "ask_explicit", // high sensitivity, require explicit per-field confirmation
  "skip", // not relevant / no profile data
  "never_fill", // secrets — formfillm must never fill these
  "manual_review", // unclear, user must decide manually
] as const;
export type RecommendedAction = (typeof RECOMMENDED_ACTIONS)[number];

// ---------------------------------------------------------------------------
// Field metadata — produced by the scanner. CONTAINS NO PERSONAL VALUES.
// `hasValue` records only whether the field is currently non-empty, never the
// value itself. This object is what gets sent to the local LLM.
// ---------------------------------------------------------------------------

export const FIELD_KINDS = [
  "text",
  "textarea",
  "select",
  "checkbox",
  "radio",
  "aria-radio",
  "aria-listbox",
] as const;
export type FieldKind = (typeof FIELD_KINDS)[number];

export interface FieldOption {
  /** Option label as shown to the user. */
  label: string;
  /** Underlying value for native <option>; omitted for ARIA widgets. */
  value?: string;
}

export interface FieldRect {
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface FieldMetadata {
  /** Stable id generated by the content script for this scan session. */
  fieldId: string;
  kind: FieldKind;
  tagName: string;
  inputType: string | null;
  name: string | null;
  domId: string | null;
  autocomplete: string | null;
  placeholder: string | null;
  ariaLabel: string | null;
  ariaLabelledByText: string | null;
  labelText: string | null;
  nearbyText: string | null;
  sectionHeading: string | null;
  required: boolean;
  disabled: boolean;
  readonly: boolean;
  /** Whether the field already holds a value. NEVER the value itself. */
  hasValue: boolean;
  /** Present for select / radio / checkbox-group / ARIA widgets. */
  options?: FieldOption[];
  rect: FieldRect;
  visible: boolean;
  /** Narrow form context — id/name only, never field values. */
  formContext: string | null;
}

// ---------------------------------------------------------------------------
// Classification — produced by the local LLM, validated before use.
// ---------------------------------------------------------------------------

export interface FieldClassification {
  fieldId: string;
  category: FieldCategory;
  sensitivity: Sensitivity;
  /** 0..1 */
  confidence: number;
  plainLanguageReason: string;
  possiblePurpose: string;
  recommendedAction: RecommendedAction;
  profileKeySuggestion: string | null;
  warnings: string[];
}

// ---------------------------------------------------------------------------
// Profile — the user's local data. Stored ONLY in chrome.storage.local.
// ---------------------------------------------------------------------------

export const PROFILE_KEYS = [
  "identity.full_name",
  "identity.first_name",
  "identity.last_name",
  "contact.email",
  "contact.phone",
  "address.street",
  "address.unit",
  "address.city",
  "address.region",
  "address.postal_code",
  "address.country",
  "locale.language",
  "locale.region",
  "preference.communication",
  "employment.job_title",
  "employment.company",
] as const;
export type ProfileKey = (typeof PROFILE_KEYS)[number];

export interface Profile {
  /** Known keys plus user-defined custom key/value pairs. */
  values: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Disclosure ledger — records categories and decisions, NEVER actual values.
// ---------------------------------------------------------------------------

export const LEDGER_DECISIONS = [
  "approved",
  "edited",
  "skipped",
  "marked_wrong",
  "never_fill",
] as const;
export type LedgerDecision = (typeof LEDGER_DECISIONS)[number];

export interface LedgerEntry {
  /** Epoch milliseconds. */
  timestamp: number;
  siteOrigin: string;
  pageTitle: string | null;
  fieldLabel: string;
  category: FieldCategory;
  sensitivity: Sensitivity;
  decision: LedgerDecision;
  /** Always false in this MVP — proof we do not persist values. */
  valueStored: false;
  filled: boolean;
}

// ---------------------------------------------------------------------------
// Settings — Ollama config and local-only enforcement.
// ---------------------------------------------------------------------------

export interface Settings {
  ollamaBaseUrl: string;
  model: string;
  temperature: number;
  /** Locked on for the MVP — surfaced in UI but not user-disablable. */
  localOnly: true;
  /** Use Ollama structured/JSON output mode when supported. */
  jsonSchemaMode: boolean;
}

export const DEFAULT_SETTINGS: Settings = {
  ollamaBaseUrl: "http://127.0.0.1:11434",
  model: "qwen3.5:9b",
  temperature: 0,
  localOnly: true,
  jsonSchemaMode: true,
};

// Storage keys (chrome.storage.local).
export const STORAGE_KEYS = {
  settings: "formfillm.settings",
  profile: "formfillm.profile",
  ledger: "formfillm.ledger",
} as const;
